pub mod click;
pub mod focus;
pub mod form;
pub mod input;
pub mod keys;
pub mod physical;
pub mod pointer;
pub mod read;
pub mod scroll;
pub mod target;
pub mod upload;

pub use click::click;
pub use focus::focus;
pub use form::{check, select_option, uncheck};
pub use input::type_text;
pub use keys::{press_enter, press_key};
pub use pointer::{PointerClickKind, click_kind, hover};
pub use read::{read_text, read_value};
pub use scroll::{PageScrollDirection, scroll_target_into_view, scroll_window};
pub use upload::upload;
